decamincow:
  name: decmincow
  gender: 1
  arrayInt: 0,1,2,3,6
  mapProps:
    key: value1
    key2: value2
  mapList:
  - key: key1
    value: value1
  - key: key2
    value: value2
  stringList:
  - string1
  - string2
  randomString: ${random.value}
  randomInt: ${random.int} # ${random.long} ${random.int(10)} ${random.int[10,20]}